/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.alexlandau.commonscompressrepro;

import org.junit.Test;

public class ReprosTest {
    @Test
    public void testLoadingTheClass() {
        Repros.loadTheSegmentClass();
    }

    @Test
    public void testActuallyUsingPack200() {
        Repros.doSomePacking();
    }
}
